'use client';
import {FormEvent,useState} from 'react';
import {useRouter} from 'next/navigation';

type User={id:number;username:string;display_name:string|null;role:string;enabled:boolean};
export default function AdminUserManager({users}:{users:User[]}){
  const router=useRouter();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setNotice('');const form=new FormData(event.currentTarget);const payload={username:String(form.get('username')||''),password:String(form.get('password')||''),display_name:String(form.get('display_name')||'')||null,role:String(form.get('role')||'learner')};const r=await fetch('/api/admin-proxy/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setBusy(false);if(!r.ok){const d=await r.json().catch(()=>({detail:'创建失败'}));setError(d.detail??'创建失败');return;}event.currentTarget.reset();setNotice('账号已创建');router.refresh();}
  async function toggle(user:User){setError('');setNotice('');const r=await fetch(`/api/admin-proxy/users/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!user.enabled})});if(!r.ok){const d=await r.json().catch(()=>({detail:'更新账号状态失败'}));setError(d.detail??'更新账号状态失败');return;}router.refresh();}
  async function resetPassword(user:User){
    const value=window.prompt(`为 @${user.username} 设置新密码：`);if(value===null)return;setError('');setNotice('');
    const r=await fetch(`/api/admin-proxy/users/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:value})});
    if(!r.ok){const d=await r.json().catch(()=>({detail:'重置失败'}));setError(d.detail??'重置失败');return;}setNotice(`已重置 @${user.username} 的密码`);router.refresh();}
  return <><form className="card formGrid" onSubmit={create}><input className="textInput" name="username" required placeholder="用户名（字母/数字/._-）"/><input className="textInput" name="display_name" placeholder="显示名称"/><input className="textInput" name="password" type="password" placeholder="初始密码（学习账号可留空；管理员必填）"/><select className="textInput" name="role" defaultValue="learner"><option value="learner">学习账号</option><option value="admin">管理员</option></select><button className="button nativeButton" disabled={busy}>{busy?'创建中…':'创建账号'}</button></form>{notice&&<p className="statusText" style={{color:'#067647',marginTop:10}}>{notice}</p>}{error&&<p className="errorText">{error}</p>}<section className="list">{users.map(u=><article className="paper" key={u.id}><div><strong>{u.display_name??u.username}</strong><div className="muted">@{u.username} · {u.role} · {u.enabled?'启用':'停用'}</div></div><div className="row" style={{gap:10}}><button className="ghostButton" onClick={()=>resetPassword(u)}>重置密码</button>{u.username!=='local'&&<button className="ghostButton" onClick={()=>toggle(u)}>{u.enabled?'停用':'启用'}</button>}</div></article>)}</section></>}
