'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';

type Paper={id:number;title:string;subject_code:string;paper_type:string;total_score:number|null;time_limit_minutes:number|null;status:string;version:number;section_count:number;question_count:number};
export default function AdminPaperRow({paper}:{paper:Paper}){const router=useRouter();const [title,setTitle]=useState(paper.title);const [status,setStatus]=useState(paper.status);const [time,setTime]=useState(paper.time_limit_minutes?.toString()??'');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function save(){setBusy(true);const r=await fetch(`/api/admin-proxy/papers/${paper.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,status,time_limit_minutes:time?Number(time):null})});setBusy(false);if(!r.ok){setMessage('保存失败');return;}setMessage('已保存');router.refresh();}
 async function archive(){if(!confirm('确认归档该试卷？历史作答不会删除。'))return;setBusy(true);const r=await fetch(`/api/admin-proxy/papers/${paper.id}`,{method:'DELETE'});setBusy(false);if(!r.ok){setMessage('归档失败');return;}router.refresh();}
 return <article className="card adminRow"><div className="row"><div><div className="eyebrow">#{paper.id} · {paper.subject_code} · v{paper.version}</div><strong>{paper.question_count} 题 · {paper.section_count} 大题 · {paper.total_score??'—'} 分</strong></div>{paper.status==='published'&&<Link className="ghostButton" href={`/papers/${paper.id}`}>查看试卷</Link>}</div><label>标题<input className="textInput" value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="formGrid"><label>状态<select className="textInput" value={status} onChange={e=>setStatus(e.target.value)}><option value="draft">draft</option><option value="published">published</option><option value="archived">archived</option></select></label><label>时长（分钟）<input className="textInput" type="number" min="1" value={time} onChange={e=>setTime(e.target.value)}/></label></div><div className="row adminActions"><button className="button nativeButton" disabled={busy} onClick={save}>保存</button><button className="ghostButton danger" disabled={busy||paper.status==='archived'} onClick={archive}>归档</button></div>{message&&<p className="muted">{message}</p>}</article>}
