'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import RichHtml from './RichHtml';

type Question={id:number;subject_code:string;type:string;stem_html:string;material_html:string|null;answer_mode:string;standard_answer_json:any;explanation_html:string|null;score:number;difficulty:string|null;knowledge_points:string[]|null;source:string|null;status:string;version:number;options:any[]};
export default function AdminQuestionEditor({question}:{question:Question}){const router=useRouter();const [stem,setStem]=useState(question.stem_html);const [material,setMaterial]=useState(question.material_html??'');const [type,setType]=useState(question.type);const [mode,setMode]=useState(question.answer_mode);const [score,setScore]=useState(String(question.score));const [status,setStatus]=useState(question.status);const [standard,setStandard]=useState(JSON.stringify(question.standard_answer_json,null,2));const [explanation,setExplanation]=useState(question.explanation_html??'');const [knowledge,setKnowledge]=useState((question.knowledge_points??[]).join(', '));const [options,setOptions]=useState(JSON.stringify(question.options.map(({label,content_html,order_index})=>({label,content_html,order_index})),null,2));const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function save(){setBusy(true);setMessage('');try{const body={type,stem_html:stem,material_html:material||null,answer_mode:mode,standard_answer_json:standard.trim()?JSON.parse(standard):null,explanation_html:explanation||null,score:Number(score),knowledge_points:knowledge.split(/[,，]/).map(x=>x.trim()).filter(Boolean),status,options:JSON.parse(options)};const r=await fetch(`/api/admin-proxy/questions/${question.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const payload=await r.json();if(!r.ok)throw new Error(payload.detail??'保存失败');setMessage(`已保存为 v${payload.version}`);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'保存失败')}finally{setBusy(false)}}
 async function archive(){if(!confirm('确认归档该题？历史作答不会删除。'))return;setBusy(true);const r=await fetch(`/api/admin-proxy/questions/${question.id}`,{method:'DELETE'});setBusy(false);if(!r.ok){setMessage('归档失败');return;}router.refresh();}
 return <><section className="card"><div className="row"><div><div className="eyebrow">Question #{question.id} · {question.subject_code} · v{question.version}</div><h2>实时预览</h2></div><span className={`badge ${question.status==='published'?'mastered':question.status==='archived'?'pending':''}`}>{question.status}</span></div><RichHtml html={stem}/>{question.options.length>0&&<div className="optionList">{question.options.map(o=><div key={o.id}><b>{o.label}.</b> <RichHtml html={o.content_html}/></div>)}</div>}</section><section className="card reviewForm"><div className="formGrid"><label>题型<input className="textInput" value={type} onChange={e=>setType(e.target.value)}/></label><label>状态<select className="textInput" value={status} onChange={e=>setStatus(e.target.value)}><option value="draft">draft</option><option value="published">published</option><option value="archived">archived</option></select></label></div><label>题干 HTML<textarea className="textArea" rows={5} value={stem} onChange={e=>setStem(e.target.value)}/></label><label>材料 HTML<textarea className="textArea" rows={4} value={material} onChange={e=>setMaterial(e.target.value)}/></label><div className="formGrid"><label>判分模式<input className="textInput" value={mode} onChange={e=>setMode(e.target.value)}/></label><label>分值<input className="textInput" type="number" step="0.5" min="0" value={score} onChange={e=>setScore(e.target.value)}/></label></div><label>标准答案 JSON<textarea className="textArea codeArea" rows={5} value={standard} onChange={e=>setStandard(e.target.value)}/></label><label>选项 JSON<textarea className="textArea codeArea" rows={10} value={options} onChange={e=>setOptions(e.target.value)}/></label><label>解析 HTML<textarea className="textArea" rows={5} value={explanation} onChange={e=>setExplanation(e.target.value)}/></label><label>知识点<input className="textInput" value={knowledge} onChange={e=>setKnowledge(e.target.value)}/></label><div className="row adminActions"><button className="button nativeButton" disabled={busy} onClick={save}>保存修改</button><button className="ghostButton danger" disabled={busy||question.status==='archived'} onClick={archive}>归档题目</button></div>{message&&<p className="muted">{message}</p>}</section></>}
