'use client';
import {FormEvent,useState} from 'react';
import {useRouter} from 'next/navigation';

type User={id:number;username:string;display_name:string|null;role:string;enabled:boolean};
export default function AdminUserManager({users}:{users:User[]}){const router=useRouter();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);const payload={username:String(form.get('username')||''),password:String(form.get('password')||''),display_name:String(form.get('display_name')||'')||null,role:String(form.get('role')||'learner')};const r=await fetch('/api/admin-proxy/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setBusy(false);if(!r.ok){const d=await r.json().catch(()=>({detail:'创建失败'}));setError(d.detail??'创建失败');return;}event.currentTarget.reset();router.refresh();}
async function toggle(user:User){const r=await fetch(`/api/admin-proxy/users/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!user.enabled})});if(!r.ok){setError('更新账号状态失败');return;}router.refresh();}
return <><form className="card formGrid" onSubmit={create}><input className="textInput" name="username" required placeholder="用户名（字母/数字/._-）"/><input className="textInput" name="display_name" placeholder="显示名称"/><input className="textInput" name="password" required type="password" minLength={8} placeholder="初始密码（至少8位）"/><select className="textInput" name="role" defaultValue="learner"><option value="learner">学习账号</option><option value="admin">管理员</option></select><button className="button nativeButton" disabled={busy}>{busy?'创建中…':'创建账号'}</button>{error&&<p className="errorText">{error}</p>}</form><section className="list">{users.map(u=><article className="paper" key={u.id}><div><strong>{u.display_name??u.username}</strong><div className="muted">@{u.username} · {u.role} · {u.enabled?'启用':'停用'}</div></div>{u.username!=='local'&&<button className="ghostButton" onClick={()=>toggle(u)}>{u.enabled?'停用':'启用'}</button>}</article>)}</section></>}
